spring:
  datasource:
    url: jdbc:mysql://127.0.01:3306/shop
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/example/multidb/auto/mapper/*.xml
  type-aliases-package: com.example.multidb.auto.entity
#spring.jpa.show-sql: true