spring:
  datasource:
    hikari:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3316/db?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password:
        maximum-pool-size: 50
        max-lifetime: 30000
        idle-timeout: 28000
        connection-timeout: 0
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3326/db?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password:
        maximum-pool-size: 50
        max-lifetime: 30000
        idle-timeout: 28000
        connection-timeout: 0
mybatis:
  mapper-locations: classpath:com/example/multidb/auto/mapper/*.xml
  type-aliases-package: com.example.multidb.auto.entity
#spring.jpa.show-sql: true